Update bro.py: Fix undefined name in Python code (#1240)
`outfile` is used before it is defined on the following line so use `options.outfile` instead.

% `ruff check`
```
Error: python/bro.py:168:64: F821 Undefined name `outfile`
```

Co-authored-by: Eugene Kliuchnikov <eustas.ru@gmail.com>